/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import service.MealService;
import model.Meal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import ui.addEmployeeDialog;
import ui.AddCustomerDialog;
import ui.AddMealDialog;

public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        loadMealData();    
        loadEmployeeData(); 
        loadCustomerData();  
    }

private void loadMealData() {
    try {
        service.MealService mealService = new service.MealService();
        java.util.List<model.Meal> meals = mealService.getAvailableMenu();
        
        String[] columnNames = {"ID", "Name", "Price", "Category", "Available"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        for (model.Meal meal : meals) {
            Object[] row = {
                meal.getMealId(),
                meal.getName(),
                meal.getPrice(),
                meal.getCategory(),
                meal.isAvailable() ? "Yes" : "No"
            };
            model.addRow(row);
        }
        tblMeals.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading meals: " + e.getMessage());
    }
}
    
    private void loadEmployeeData() {
       try {
        repository.UserRepository userRepo = new repository.UserRepository();
        java.util.List<model.User> allUsers = userRepo.getAllUsers();

        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        model.setRowCount(0);

        for (model.User u : allUsers) {
            if (u instanceof model.Employee) {
                model.Employee emp = (model.Employee) u;
                Object[] row = {
                    emp.getId(),
                    emp.getName(),
                    emp.getUserRole(),
                    emp.getSalary()
                };
                model.addRow(row);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading employees: " + e.getMessage());
    }
    }
   
    private void loadCustomerData() {
     try {
        repository.UserRepository userRepo = new repository.UserRepository();
        java.util.List<model.User> allUsers = userRepo.getAllUsers();
        
        DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();
        model.setRowCount(0);
        
        for (model.User u : allUsers) {
            if ("CUSTOMER".equalsIgnoreCase(u.getUserRole())) {
                Object[] row = {
                    u.getId(),
                    u.getName(),
                    u.getPhone(), 
                    0 
                };
                model.addRow(row);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading customers: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMeals = new javax.swing.JTable();
        btnAddMeal = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        deleteMeal = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnAddEmp = new javax.swing.JButton();
        btnDeleteEmp = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        btnAddCust = new javax.swing.JButton();
        lblStats = new javax.swing.JLabel();
        lblTotalSalaries = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        logAction = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMeals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMeals);

        btnAddMeal.setText("add meal");
        btnAddMeal.addActionListener(this::btnAddMealActionPerformed);

        btnPDF.setText("export pdf");
        btnPDF.addActionListener(this::btnPDFActionPerformed);

        deleteMeal.setText("delete meal");
        deleteMeal.addActionListener(this::deleteMealActionPerformed);

        btnRefresh.setText("refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEmployees);

        btnAddEmp.setText("add emp");
        btnAddEmp.addActionListener(this::btnAddEmpActionPerformed);

        btnDeleteEmp.setText("del emp");
        btnDeleteEmp.addActionListener(this::btnDeleteEmpActionPerformed);

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblCustomers);

        btnAddCust.setText("add cust");
        btnAddCust.addActionListener(this::btnAddCustActionPerformed);

        lblStats.setText("lblStats");

        lblTotalSalaries.setText("lblTotalSalaries");

        jButton2.setText("export csv");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        logAction.setText("log action");
        logAction.addActionListener(this::logActionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddMeal)
                                .addGap(18, 18, 18)
                                .addComponent(deleteMeal)
                                .addGap(94, 94, 94)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btnAddEmp)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteEmp))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStats)
                            .addComponent(lblTotalSalaries))
                        .addGap(159, 159, 159)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCust)
                .addGap(409, 409, 409))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMeal)
                    .addComponent(deleteMeal)
                    .addComponent(btnAddEmp)
                    .addComponent(btnDeleteEmp))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddCust)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblStats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalSalaries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(logAction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
    try {
            exportDataToPDF(); 
            JOptionPane.showMessageDialog(this, "Report exported successfully to PDF!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "PDF Error: " + e.getMessage());
        }    }//GEN-LAST:event_btnPDFActionPerformed

    private void deleteMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMealActionPerformed
        int selectedRow = tblMeals.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a meal to delete.");
            return;
        }

        int id = Integer.parseInt(tblMeals.getValueAt(selectedRow, 0).toString());
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this meal?");

        if (confirm == JOptionPane.YES_OPTION) {
            MealService mealService = new MealService();
        if (mealService.deleteMeal(id)) {
            JOptionPane.showMessageDialog(this, "Meal deleted successfully!");
            loadMealData();
    }
}    }//GEN-LAST:event_deleteMealActionPerformed

    private void btnAddMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMealActionPerformed
        new AddMealDialog().setVisible(true);
    }//GEN-LAST:event_btnAddMealActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadMealData();
        loadEmployeeData();
        loadCustomerData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
addEmployeeDialog addEmpDlg = new addEmployeeDialog(); 
addEmpDlg.setVisible(true);    addEmpDlg.setLocationRelativeTo(this);
    addEmpDlg.setVisible(true); 
    
    loadEmployeeData();
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void btnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpActionPerformed
int selectedRow = tblEmployees.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select an employee from the table first!");
        return;
    }

    try {
        Object idObj = tblEmployees.getValueAt(selectedRow, 0);
        int id = Integer.parseInt(idObj.toString());

        // 3. تأكيد الحذف
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete employee ID: " + id + "?", 
            "Confirm Deletion", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            service.EmployeeService empService = new service.EmployeeService();
            if (empService.deleteEmployee(id)) {
                JOptionPane.showMessageDialog(this, "Employee deleted successfully!");
                loadEmployeeData(); 
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete. Employee might not exist.");
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error during deletion: " + e.getMessage());
    
    }    }//GEN-LAST:event_btnDeleteEmpActionPerformed

    private void btnAddCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustActionPerformed
AddCustomerDialog addCustDlg = new AddCustomerDialog();
addCustDlg.setVisible(true);
addCustDlg.setLocationRelativeTo(this);
    addCustDlg.setVisible(true);
    
    loadCustomerData();
    }//GEN-LAST:event_btnAddCustActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String fileName = "Restaurant_Data.csv";
    try (java.io.PrintWriter writer = new java.io.PrintWriter(new java.io.File(fileName))) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("Type,ID,Name,Price/Info\n");
        for (int i = 0; i < tblMeals.getRowCount(); i++) {
            sb.append("Meal,")
              .append(tblMeals.getValueAt(i, 0)).append(",")
              .append(tblMeals.getValueAt(i, 1)).append(",")
              .append(tblMeals.getValueAt(i, 2)).append("\n");
        }

        for (int i = 0; i < tblEmployees.getRowCount(); i++) {
            sb.append("Employee,")
              .append(tblEmployees.getValueAt(i, 0)).append(",")
              .append(tblEmployees.getValueAt(i, 1)).append(",")
              .append(tblEmployees.getValueAt(i, 3)).append("\n");
        }

        writer.write(sb.toString());
        JOptionPane.showMessageDialog(this, "Data exported to CSV successfully!");
    } catch (java.io.FileNotFoundException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionActionPerformed

    }//GEN-LAST:event_logActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }
    
    private void updateAnalytics() {
    double totalSalaries = 0;
    String mostExpensiveMeal = "N/A";
    double maxPrice = 0;

    for (int i = 0; i < tblEmployees.getRowCount(); i++) {
        try {
            totalSalaries += Double.parseDouble(tblEmployees.getValueAt(i, 3).toString());
        } catch (Exception e) {}
    }

    for (int i = 0; i < tblMeals.getRowCount(); i++) {
        try {
            double price = Double.parseDouble(tblMeals.getValueAt(i, 2).toString());
            if (price > maxPrice) {
                maxPrice = price;
                mostExpensiveMeal = tblMeals.getValueAt(i, 1).toString();
            }
        } catch (Exception e) {}
    }

    lblTotalSalaries.setText("Total Salaries: " + totalSalaries + " EGP");
    lblStats.setText("Most Expensive: " + mostExpensiveMeal + " (" + maxPrice + " EGP)");
}
    
private void exportDataToPDF() {
    String fileName = "Restaurant_Report.txt";
    try (java.io.PrintWriter writer = new java.io.PrintWriter(new java.io.FileWriter(fileName))) {
        writer.println("==================================================");
        writer.println("            RESTAURANT SUMMARY REPORT             ");
        writer.println("==================================================");
        writer.println("Date: " + new java.util.Date());
        
        writer.println("\n--- FINANCIAL SUMMARY ---");
        writer.println(lblTotalSalaries.getText());
        writer.println(lblStats.getText());
        writer.println("Total Employees: " + tblEmployees.getRowCount());
        writer.println("Total Customers: " + tblCustomers.getRowCount());
        writer.println("--------------------------------------------------");

        writer.println("\n--- MEALS LIST ---");
        for (int i = 0; i < tblMeals.getRowCount(); i++) {
            writer.println("- " + tblMeals.getValueAt(i, 1) + " | Price: " + tblMeals.getValueAt(i, 2) + " EGP");
        }

        writer.println("\n--- EMPLOYEES LIST ---");
        for (int i = 0; i < tblEmployees.getRowCount(); i++) {
            writer.println("- " + tblEmployees.getValueAt(i, 1) + " | Role: " + tblEmployees.getValueAt(i, 2) + " | Salary: " + tblEmployees.getValueAt(i, 3));
        }

        writer.println("\n--- CUSTOMERS LIST ---");
        for (int i = 0; i < tblCustomers.getRowCount(); i++) {
            writer.println("- " + tblCustomers.getValueAt(i, 1) + " | Phone: " + tblCustomers.getValueAt(i, 2));
        }
        
        writer.println("\n==================================================");
        writer.println("         Generated by: " + (service.AuthService.getCurrentUser() != null ? service.AuthService.getCurrentUser().getName() : "Admin"));
        writer.println("==================================================");
        
        JOptionPane.showMessageDialog(this, "Report saved successfully to: " + fileName);
    } catch (java.io.IOException e) {
        JOptionPane.showMessageDialog(this, "Export Error: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCust;
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnAddMeal;
    private javax.swing.JButton btnDeleteEmp;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton deleteMeal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblStats;
    private javax.swing.JLabel lblTotalSalaries;
    private javax.swing.JButton logAction;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTable tblMeals;
    // End of variables declaration//GEN-END:variables
}
