/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import service.MealService;
import model.Meal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        loadMealData();      // دي موجودة عندك
        loadEmployeeData();  // زود دي
        loadCustomerData();  // وزود دي
    }

    private void loadMealData() {
    try {
        service.MealService mealService = new service.MealService();
        java.util.List<model.Meal> meals = mealService.getAvailableMenu();
        
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMeals.getModel();
        model.setRowCount(0);
        
        for (model.Meal meal : meals) {
            Object[] row = {
                meal.getMealId(),
                meal.getName(),
                meal.getPrice(),
                meal.getCategory(),
                meal.isAvailable() ? "Yes" : "No"
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
    }
}
    
    private void loadEmployeeData() {
    try {
        service.EmployeeService empService = new service.EmployeeService();
        java.util.List<model.Employee> employees = empService.getAllEmployees();
        
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        model.setRowCount(0);
        
        for (model.Employee emp : employees) {
            Object[] row = {
                emp.getId(),
                emp.getName(),
                emp.getRole(),
                emp.getSalary()
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading employees: " + e.getMessage());
    }
}
    private void loadCustomerData() {
    try {
        service.CustomerService custService = new service.CustomerService();
        java.util.List<model.Customer> customers = custService.getAllCustomers();
        
        DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();
        model.setRowCount(0);
        
        for (model.Customer cust : customers) {
            Object[] row = {
                cust.getId(),
                cust.getName(),
                cust.getPhone(),
                cust.getLoyaltyPoints()
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading customers: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMeals = new javax.swing.JTable();
        btnAddMeal = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        deleteMeal = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnAddEmp = new javax.swing.JButton();
        btnDeleteEmp = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        btnAddCust = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMeals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMeals);

        btnAddMeal.setText("add meal");
        btnAddMeal.addActionListener(this::btnAddMealActionPerformed);

        btnPDF.setText("export pdf");
        btnPDF.addActionListener(this::btnPDFActionPerformed);

        deleteMeal.setText("delete meal");
        deleteMeal.addActionListener(this::deleteMealActionPerformed);

        btnRefresh.setText("refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEmployees);

        btnAddEmp.setText("add emp");
        btnAddEmp.addActionListener(this::btnAddEmpActionPerformed);

        btnDeleteEmp.setText("del emp");
        btnDeleteEmp.addActionListener(this::btnDeleteEmpActionPerformed);

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblCustomers);

        btnAddCust.setText("add cust");
        btnAddCust.addActionListener(this::btnAddCustActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddMeal)
                                .addGap(18, 18, 18)
                                .addComponent(deleteMeal)
                                .addGap(94, 94, 94)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btnAddEmp)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteEmp))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(btnAddCust)))))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMeal)
                    .addComponent(deleteMeal)
                    .addComponent(btnAddEmp)
                    .addComponent(btnDeleteEmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAddCust)
                .addGap(29, 29, 29)
                .addComponent(btnPDF)
                .addGap(5, 5, 5)
                .addComponent(btnRefresh))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
    try {
            // هنستخدم ميثود بتبني ملف نصي أو PDF بسيط
            // هحطلك كود الميثود دي تحت
            exportDataToPDF(); 
            JOptionPane.showMessageDialog(this, "Report exported successfully to PDF!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "PDF Error: " + e.getMessage());
        }    }//GEN-LAST:event_btnPDFActionPerformed

    private void deleteMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMealActionPerformed
        int selectedRow = tblMeals.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a meal to delete.");
            return;
        }

        int id = (int) tblMeals.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this meal?");

        if (confirm == JOptionPane.YES_OPTION) {
            MealService mealService = new MealService();
        if (mealService.deleteMeal(id)) {
            JOptionPane.showMessageDialog(this, "Meal deleted successfully!");
            loadMealData();
    }
}    }//GEN-LAST:event_deleteMealActionPerformed

    private void btnAddMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMealActionPerformed
        new AddMealDialog().setVisible(true);
    }//GEN-LAST:event_btnAddMealActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadMealData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        String name = JOptionPane.showInputDialog(this, "Enter Employee Name:");
        if (name != null && !name.isEmpty()) {
            loadEmployeeData();
        }
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void btnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpActionPerformed
    int selectedRow = tblEmployees.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select an employee to delete.");
        return;
    }

    int id = (int) tblEmployees.getValueAt(selectedRow, 0);
    if (JOptionPane.showConfirmDialog(this, "Delete this employee?") == JOptionPane.YES_OPTION) {
        if (new service.EmployeeService().deleteEmployee(id)) {
            loadEmployeeData(); // ريفرش للجدول
        }
    }    }//GEN-LAST:event_btnDeleteEmpActionPerformed

    private void btnAddCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustActionPerformed
        String name = JOptionPane.showInputDialog(this, "Enter Customer Name:");
        String phone = JOptionPane.showInputDialog(this, "Enter Customer Phone:");
        if (name != null && phone != null) {
            // كود الحفظ من خلال السيرفيس
            loadCustomerData(); // ريفرش
        }
    }//GEN-LAST:event_btnAddCustActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }
    private void exportDataToPDF() {
 
    System.out.println("Generating PDF Report for Meals, Employees, and Customers...");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCust;
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnAddMeal;
    private javax.swing.JButton btnDeleteEmp;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton deleteMeal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTable tblMeals;
    // End of variables declaration//GEN-END:variables
}
