/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author shon
 */
public class customerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(customerDashboard.class.getName());

    /**
     * Creates new form customerDashboard
     */
public customerDashboard() {
    initComponents();

    loadMealData();

    tblMeals.setSelectionMode(
        javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION
    );
}
    private void loadMealData() {
        try {
            service.MealService mealService = new service.MealService();
            java.util.List<model.Meal> meals = mealService.getAvailableMenu();
        
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMeals.getModel();
            model.setRowCount(0);
        
            for (model.Meal meal : meals) {
                Object[] row = {
                    meal.getMealId(),
                    meal.getName(),
                    meal.getPrice(),
                    meal.getCategory(),
                    meal.isAvailable() ? "Yes" : "No"
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMeals = new javax.swing.JTable();
        tblConfirmMeal = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMeals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMeals);

        tblConfirmMeal.setText("Confirm Order");
        tblConfirmMeal.addActionListener(this::tblConfirmMealActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblConfirmMeal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tblConfirmMeal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblConfirmMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblConfirmMealActionPerformed
        int[] selectedRows = tblMeals.getSelectedRows();
    if (selectedRows.length == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select at least one meal");
        return;
    }

    java.util.List<model.Meal> selectedMeals = new java.util.ArrayList<>();
    double totalOrderPrice = 0;

    for (int row : selectedRows) {
        try {
            int mealId = Integer.parseInt(tblMeals.getValueAt(row, 0).toString());
            String name = tblMeals.getValueAt(row, 1).toString();
            double price = Double.parseDouble(tblMeals.getValueAt(row, 2).toString());
            String categoryStr = tblMeals.getValueAt(row, 3).toString();

            enums.MealCategory cat = enums.MealCategory.valueOf(categoryStr.toUpperCase());

            model.Meal m = new model.Meal(mealId, name, "", price, cat, true);
            
            selectedMeals.add(m);
            totalOrderPrice += price;
        } catch (Exception e) {
            System.out.println("Row processing error: " + e.getMessage());
        }
    }

    try {
        model.Order newOrder = new model.Order(
            0,
            "Guest Customer", 
            selectedMeals, 
            totalOrderPrice, 
            enums.OrderStatus.PENDING
        );

        service.OrderService orderService = new service.OrderService();
        orderService.placeOrder(newOrder);

        util.LoggerUtil.log("Order Placed - Total: " + totalOrderPrice + " EGP");

        javax.swing.JOptionPane.showMessageDialog(this, "Order sent to Chef successfully!");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error placing order: " + e.getMessage());
    }
    }//GEN-LAST:event_tblConfirmMealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new customerDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tblConfirmMeal;
    private javax.swing.JTable tblMeals;
    // End of variables declaration//GEN-END:variables
}
